config/routes.rb
Rails.application.routes.draw do
  resources :kingdom_cards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'kingdom_cards#index'
  get '/play' => 'kingdom_cards#play'
  get '/get_card' => 'kingdom_cards#get_card'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kingdom_card.rb
class KingdomCard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kingdom_cards_controller.rb
class KingdomCardsController < ApplicationController
  before_action :set_kingdom_card, only: [:show, :edit, :update, :destroy]

  # GET /kingdom_cards
  # GET /kingdom_cards.json
  def index
    @kingdom_cards = KingdomCard.all
  end

  # GET /kingdom_cards/1
  # GET /kingdom_cards/1.json
  def show
  end

  # GET /kingdom_cards/new
  def new
    @kingdom_card = KingdomCard.new
  end

  # GET /kingdom_cards/1/edit
  def edit
  end

  # POST /kingdom_cards
  # POST /kingdom_cards.json
  def create
    @kingdom_card = KingdomCard.new(kingdom_card_params)

    respond_to do |format|
      if @kingdom_card.save
        format.html { redirect_to new_kingdom_card_path, notice: 'Kingdom card was successfully created.' }
        format.json { render :show, status: :created, location: @kingdom_card }
      else
        format.html { render :new }
        format.json { render json: @kingdom_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kingdom_cards/1
  # PATCH/PUT /kingdom_cards/1.json
  def update
    respond_to do |format|
      if @kingdom_card.update(kingdom_card_params)
        format.html { redirect_to @kingdom_card, notice: 'Kingdom card was successfully updated.' }
        format.json { render :show, status: :ok, location: @kingdom_card }
      else
        format.html { render :edit }
        format.json { render json: @kingdom_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kingdom_cards/1
  # DELETE /kingdom_cards/1.json
  def destroy
    @kingdom_card.destroy
    respond_to do |format|
      format.html { redirect_to kingdom_cards_url, notice: 'Kingdom card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def play
    @kingdom_cards = KingdomCard.limit(10).order("RANDOM()")
  end

  def get_card
    @kingdom_card = KingdomCard.where.not(id: [params[:card0], params[:card1], params[:card2], params[:card3], params[:card4], params[:card5], params[:card6], params[:card7], params[:card8], params[:card9]])
    @kingdom_card = @kingdom_card.order("RANDOM()").first
    render json: @kingdom_card
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kingdom_card
      @kingdom_card = KingdomCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kingdom_card_params
      if params[:kingdom_card][:sub_type].instance_of? Array
        params[:kingdom_card][:sub_type] = params[:kingdom_card][:sub_type].join(', ')
      end
      params.require(:kingdom_card).permit(:name, :set, :card_type, :sub_type, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kingdom_cards_helper.rb
module KingdomCardsHelper
end

app/views/kingdom_cards/_form.html.erb
<%= form_for(kingdom_card) do |f| %>
  <% if kingdom_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kingdom_card.errors.count, "error") %> prohibited this kingdom_card from being saved:</h2>

      <ul>
      <% kingdom_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :set %>
    <%= f.select :set, [['Base', 'Base'], ['Seaside','Seaside'], ['Prosperity', 'Prosperity'], ['Cornucopia', 'Cornucopia'], ['Empires', 'Empires']] %>
  </div>

  <div class="field">
    <%= f.label :card_type %>
    <%= f.select :card_type, [['Action', 'Action'], ['Treasure', 'Treasure'], ['Victory', 'Victory']] %>
  </div>

  <div class="field">
    <%=f.check_box :sub_type, {:multiple => true}, "Attack", nil%> Attack
    <%=f.check_box :sub_type, {:multiple => true}, "Reaction", nil%> Reaction
    <%=f.check_box :sub_type, {:multiple => true}, "Duration", nil%> Duration
    <%=f.check_box :sub_type, {:multiple => true}, "Victory", nil%> Victory
    <%=f.check_box :sub_type, {:multiple => true}, "Castle", nil%> Castle
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kingdom_cards/edit.html.erb
<h1>Editing Kingdom Card</h1>

<%= render 'form', kingdom_card: @kingdom_card %>

<%= link_to 'Show', @kingdom_card %> |
<%= link_to 'Back', kingdom_cards_path %>

app/views/kingdom_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kingdom Cards</h1>

<table id="cardList">
  <thead>
    <tr>
      <th>Name</th>
      <th>Set</th>
      <th>Card type</th>
      <th>Sub type</th>
      <th>Cost</th>
    </tr>
  </thead>

  <tbody>
    <% @kingdom_cards.each do |kingdom_card| %>
      <tr>
        <td><%= kingdom_card.name %></td>
        <td><%= kingdom_card.set %></td>
        <td><%= kingdom_card.card_type %></td>
        <td><%= kingdom_card.sub_type %></td>
        <td><%= kingdom_card.cost %></td>
        <!-- <td><%= link_to 'Show', kingdom_card %></td>
        <td><%= link_to 'Edit', edit_kingdom_card_path(kingdom_card) %></td>
        <td><%= link_to 'Destroy', kingdom_card, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add More Cards', new_kingdom_card_path %>
<%= link_to 'Lets Play!', play_path%>
<!--
<form action="/play">
    <input type="submit" value="Lets Play!" />
</form> -->

app/views/kingdom_cards/new.html.erb
<h1>New Kingdom Card</h1>

<%= render 'form', kingdom_card: @kingdom_card %>

<%= link_to 'Back', kingdom_cards_path %>

app/views/kingdom_cards/play.html.erb
<%= link_to 'New Round!', play_path%>


<table id="cardList">
  <thead>
    <tr>
      <th>Name</th>
      <th>Set</th>
      <th>Card type</th>
      <th>Sub type</th>
      <th>Cost</th>
    </tr>
  </thead>

  <tbody>
    <% @kingdom_cards.each do |kingdom_card| %>
      <tr data-card-id="<%=kingdom_card.id%>">
        <td><%= kingdom_card.name %></td>
        <td><%= kingdom_card.set %></td>
        <td><%= kingdom_card.card_type %></td>
        <td><%= kingdom_card.sub_type %></td>
        <td><%= kingdom_card.cost %></td>
        <td><button class="btn">Repick Card</button></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/kingdom_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kingdom_card.name %>
</p>

<p>
  <strong>Set:</strong>
  <%= @kingdom_card.set %>
</p>

<p>
  <strong>Card type:</strong>
  <%= @kingdom_card.card_type %>
</p>

<p>
  <strong>Sub type:</strong>
  <%= @kingdom_card.sub_type %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @kingdom_card.cost %>
</p>

<%= link_to 'Edit', edit_kingdom_card_path(@kingdom_card) %> |
<%= link_to 'Back', kingdom_cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dominion Randomizer</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>